AllCops:
  Exclude:
    - 'bin/*'
    - 'lib/tasks/cucumber.rake'
    - 'db/schema.rb'
    - 'app/controllers/graphql_controller.rb'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*'

Naming/AccessorMethodName:
  Exclude:
    - 'spec/*/*'
    - 'features/*/*'
