AllCops:
  Exclude:
    - 'bin/*'
    - 'lib/tasks/cucumber.rake'
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/*/*'

Naming/AccessorMethodName:
  Exclude:
    - 'spec/*/*'
    - 'features/*/*'
