name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Bundle install
        env:
          RAILS_ENV: test
        run: |
          gem install bundler
          bundle install

      - name: Setup Config
        run: echo "DATABASE_URL=postgres://user:password@postgres/todo_api_test" > .env.test

      - name: Run lint
        run: bundle exec rubocop

      - name: Create test database
        env:
          RAILS_ENV: test
        run: rails db:create db:migrate

      - name: Run tests
        run: rails spec
