name: CI

on:
  pull_request:
    branches: [ "main" ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create test env file
        run: echo "DATABASE_URL=postgres://user:password@postgres:5432/todo_api_test" >> .env.test

      - name: Build todo_api
        run: docker build

      - name: Check coding style
        run: docker run todo-api rubocop

      - name: Create database
        run: docker run todo-api rails db:create db:migrate RAILS_ENV=test

      - name: Run tests
        run: docker run todo-api rails spec
