# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  validate:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Create env file
        run: echo "DATABASE_URL=postgres://postgres@postgres:5432/todo_api_test" >> .env.test

      - name: Build docker containers
        run: docker-compose build

      #- name: Create database
      #  run: docker-compose run todo-api rails db:create db:migrate RAILS_ENV=test

      - name: Check coding style
        run: rubocop

      - name: Run tests
        run: docker-compose run todo-api rails spec
