name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: ruby:3.1.2

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    env:
      RAILS_ENV: test
      HOST_URL: http://localhost:3000
      DATABASE_URL: postgres://user:password@postgres/todo_api_test

    steps:
      - uses: actions/checkout@v3

      - name: Bundle install
        run: |
          gem install bundler
          bundle install

      - name: Create test database
        run: rails db:create db:migrate

      - name: Run rspec, cucumber, rubocop
        run: rake
